#Database configuration
cmd_deb_frontend : export DEBIAN_FRONTEND="noninteractive"
db_debconf_pwd : echo 'mariadb-server mysql-server/root_password password {0}'| sudo debconf-set-selections
db_debconf_pwd_again : echo 'mariadb-server mysql-server/root_password_again password {0}'| sudo debconf-set-selections
cmd_db_install : sudo apt-get install -y mariadb-server
cmd_db_dep : sudo apt-get -f install
cmd_create_db : sudo mysql -uroot -p{0} -e 'CREATE DATABASE {1} DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci'
cmd_db_grant_privileges : mysql -uroot -p{0} -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '{1}' WITH GRANT OPTION;"
cmd_db_replace_bind_addr : sudo sed -i 's/^bind-address/#&/' /etc/mysql/my.cnf
cmd_db_service : sudo systemctl restart mysql.service
## grant all on `*`.`*` to 'root'@'%' identified by 'PASSWORD' with grant option;

#----------------------------------------------------------------------------------------------------------------------------------------------
#Ejabberd configuration
cmd_ejabberd_install : sudo apt-get install -y ejabberd=18.01-0
jabberd_des_path : /tmp
jabberd_conf_path : /opt/ejabberd #/opt/ejabberd-16.06
cmd_cp_conf : sudo cp {0}/ejabberd.yml {1}/conf
cmd_chown_ejabberd : sudo chown -R ejabberd:ejabberd {0}/conf
cmd_bin_ejabberd_path: /opt/ejabberd-18.01
cmd_register : sudo {0}/bin/ejabberdctl register {1} {2} {3}
cmd_jabberd_start: sudo {0}/bin/ejabberdctl start
cmd_jabberd_restart: sudo {0}/bin/ejabberdctl restart
cmd_jabberd_status: sudo {0}/bin/ejabberdctl status
cmd_srg_create: sudo {0}/bin/ejabberdctl srg-create everyone {1} "everyone" this_is_everyone everyone
cmd_srg_user_add: sudo {0}/bin/ejabberdctl srg-user-add @all@ {1} everyone {1}
cmd_hold_ejabberd: sudo apt-mark hold ejabberd

#----------------------------------------------------------------------------------------------------------------------------------------------
#OpenLdap configuration
cmd_ldap_install : sudo apt-get install -y slapd ldap-utils
cmd_ldap_reconf: sudo dpkg-reconfigure -f noninteractive slapd
ldap_deb_frontend : export DEBIAN_FRONTEND="noninteractive"
ldap_debconf_generated_password: echo 'slapd slapd/internal/generated_adminpw password {0}' | sudo debconf-set-selections
ldap_debconf_admin_password: echo 'slapd slapd/internal/adminpw password {0}' | sudo debconf-set-selections
# ldap_debconf_pwd1 and ldap_debconf_pwd2 is admin password
ldap_debconf_pwd1: echo 'slapd slapd/password1 password {0}' | sudo debconf-set-selections
ldap_debconf_pwd2: echo 'slapd slapd/password2 password {0}' | sudo debconf-set-selections
ldap_debconf_domain: echo 'slapd slapd/domain string {0}' | sudo debconf-set-selections
ldap_debconf_organization: echo 'slapd shared/organization string {0}' | sudo debconf-set-selections
ldap_debconf_purgedb: echo 'slapd slapd/purge_database boolean true' | sudo debconf-set-selections
ldap_debconf_movedb: echo 'slapd slapd/move_old_database boolean false' | sudo debconf-set-selections
ldap_debconf_selectdb: echo 'slapd slapd/backend select MDB' | sudo debconf-set-selections
ldap_debconf_conf: echo 'slapd slapd/no_configuration boolean false' | sudo debconf-set-selections
cmd_update_ldap_execute : sudo chmod +x /tmp/update_ldap
cmd_update_ldap_run: sudo /bin/bash /tmp/update_ldap
cmd_ldapconfig_execute : sudo chmod +x /tmp/ldapconfig
cmd_ldapconfig_run: sudo /bin/bash /tmp/ldapconfig
cmd_ldap_remove: sudo apt-get purge -y slapd ldap-utils && sudo rm -rf /var/ldaps && sudo rm -rf /var/lib/ldap && sudo rm -rf /var/ldaps && sudo apt-get autoremove -y && sudo apt-get autoclean -y

#------------------------------------------------------------------------------------------------------------------------------------------------
#Lider configuration
cmd_lider_install: sudo apt-get install -y lider-server
cmd_lider_service: sudo systemctl restart lider.service
cmd_fs_dep: sudo apt-get install -y sshpass rsync
cmd_cp_lider_cfg: sudo cp /tmp/tr.org.liderahenk.cfg /usr/share/lider-server/etc
cmd_cp_db_cfg: sudo cp /tmp/tr.org.liderahenk.datasource.cfg /usr/share/lider-server/etc
lider_des_path : /tmp
cmd_agents_files: sudo mkdir -p {0}
cmd_chown_agents_files: sudo chown {0}:{0} {1}

#------------------------------------------------------------------------------------------------------------------------------------------------
# Ahenk configuration
cmd_ahenk_install: sudo apt-get install -y ahenk
cmd_ahenk_dep: sudo apt-get -f install
cmd_ahenk_register: sudo python3 /usr/share/ahenk/ahenkd.py register {0} {1} {2}

#------------------------------------------------------------------------------------------------------------------------------------------------
# Lider ahenk repository configuration
cmd_soft_properties: sudo apt-get install -y software-properties-common
cmd_liderahenk_repo_key: sudo wget {0} && sudo apt-key add {1} &&  rm -r --interactive=never {1}
cmd_liderahenk_repo_add: sudo add-apt-repository '{0}'
cmd_update: sudo apt-get update

#------------------------------------------------------------------------------------------------------------------------------------------------
# Lider Console Configuration
cmd_lider_console_install: sudo apt-get install -y lider-console
